services:
  bot:
    build: .
    container_name: discord_bot
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: python bot.py
    networks:
      - default
      - relances-net

networks:
  default:
  relances-net:
    external: true

